const knex = require("./db/db");

async function insert() {
    try {
        const data = [
            { episode: "1-qism", name: "", posts: [{ post_id: 1161 }] },
            { episode: "2-qism", name: "", posts: [{ post_id: 1162 }] },
            { episode: "3-qism", name: "", posts: [{ post_id: 1163 }] },
            { episode: "4-qism", name: "", posts: [{ post_id: 1164 }] },
            { episode: "5-qism", name: "", posts: [{ post_id: 1165 }] },
            { episode: "6-qism", name: "", posts: [{ post_id: 1166 }] },
            { episode: "7-qism", name: "", posts: [{ post_id: 1167 }] },
            { episode: "8-qism", name: "", posts: [{ post_id: 1168 }] },
            { episode: "9-qism", name: "", posts: [{ post_id: 1169 }] },
            { episode: "10-qism", name: "", posts: [{ post_id: 1170 }] },
            { episode: "11-qism", name: "", posts: [{ post_id: 1171 }] },
            { episode: "12-qism", name: "", posts: [{ post_id: 1172 }] },
            { episode: "13-qism", name: "", posts: [{ post_id: 1173 }] },
            { episode: "14-qism", name: "", posts: [{ post_id: 1174 }] },
            { episode: "15-qism", name: "", posts: [{ post_id: 1175 }] },
            { episode: "16-qism", name: "", posts: [{ post_id: 1176 }] },
            { episode: "17-qism", name: "", posts: [{ post_id: 1177 }] },
            { episode: "18-qism", name: "", posts: [{ post_id: 1178 }] },
            { episode: "19-qism", name: "", posts: [{ post_id: 1179 }] },
            { episode: "20-qism", name: "", posts: [{ post_id: 1180 }] },
            { episode: "21-qism", name: "", posts: [{ post_id: 1181 }] },
            { episode: "22-qism", name: "", posts: [{ post_id: 1182 }] },
            { episode: "23-qism", name: "", posts: [{ post_id: 1183 }] },
            { episode: "24-qism", name: "", posts: [{ post_id: 1184 }] },
            { episode: "25-qism", name: "", posts: [{ post_id: 1185 }] },
            { episode: "26-qism", name: "", posts: [{ post_id: 1186 }] },
            { episode: "27-qism", name: "", posts: [{ post_id: 1187 }] },
            { episode: "28-qism", name: "", posts: [{ post_id: 1188 }] },
            { episode: "29-qism", name: "", posts: [{ post_id: 1189 }] },
            { episode: "30-qism", name: "", posts: [{ post_id: 1190 }] },
            { episode: "31-qism", name: "", posts: [{ post_id: 1191 }] },
            { episode: "32-qism", name: "", posts: [{ post_id: 1192 }] },
            { episode: "33-qism", name: "", posts: [{ post_id: 1193 }] },
            { episode: "34-qism", name: "", posts: [{ post_id: 1194 }] },
            { episode: "35-qism", name: "", posts: [{ post_id: 1195 }] },
            { episode: "36-qism", name: "", posts: [{ post_id: 1196 }] },
            { episode: "37-qism", name: "", posts: [{ post_id: 1197 }] },
            { episode: "38-qism", name: "", posts: [{ post_id: 1198 }] },
            { episode: "39-qism", name: "", posts: [{ post_id: 1199 }] },
            { episode: "40-qism", name: "", posts: [{ post_id: 1200 }] },
            { episode: "41-qism", name: "", posts: [{ post_id: 1201 }] },
            { episode: "42-qism", name: "", posts: [{ post_id: 1202 }] },
            { episode: "43-qism", name: "", posts: [{ post_id: 1203 }] },
            { episode: "44-qism", name: "", posts: [{ post_id: 1204 }] },
            { episode: "45-qism", name: "", posts: [{ post_id: 1205 }] },
            { episode: "46-qism", name: "", posts: [{ post_id: 1206 }] },
            { episode: "47-qism", name: "", posts: [{ post_id: 1207 }] },
            { episode: "48-qism", name: "", posts: [{ post_id: 1208 }] },
            { episode: "49-qism", name: "", posts: [{ post_id: 1209 }] },
            { episode: "50-qism", name: "", posts: [{ post_id: 1210 }] },
            { episode: "51-qism", name: "", posts: [{ post_id: 1211 }] },
            { episode: "52-qism", name: "", posts: [{ post_id: 1212 }] },
            { episode: "53-qism", name: "", posts: [{ post_id: 1213 }] },
            { episode: "54-qism", name: "", posts: [{ post_id: 1214 }] },
            { episode: "55-qism", name: "", posts: [{ post_id: 1215 }] },
            { episode: "56-qism", name: "", posts: [{ post_id: 1216 }] },
            { episode: "57-qism", name: "", posts: [{ post_id: 1217 }] },
            { episode: "58-qism", name: "", posts: [{ post_id: 1218 }] },
            { episode: "59-qism", name: "", posts: [{ post_id: 1219 }] },
            { episode: "60-qism", name: "", posts: [{ post_id: 1220 }] },
            { episode: "61-qism", name: "", posts: [{ post_id: 1221 }] },
            { episode: "62-qism", name: "", posts: [{ post_id: 1222 }] },
            { episode: "63-qism", name: "", posts: [{ post_id: 1223 }] },
            { episode: "64-qism", name: "", posts: [{ post_id: 1224 }] },
            { episode: "65-qism", name: "", posts: [{ post_id: 1225 }] },
            { episode: "66-qism", name: "", posts: [{ post_id: 1226 }] },
            { episode: "67-qism", name: "", posts: [{ post_id: 1227 }] },
            { episode: "68-qism", name: "", posts: [{ post_id: 1228 }] },
            { episode: "69-qism", name: "", posts: [{ post_id: 1229 }] },
            { episode: "70-qism", name: "", posts: [{ post_id: 1230 }] },
            { episode: "71-qism", name: "", posts: [{ post_id: 1231 }] },
            { episode: "72-qism", name: "", posts: [{ post_id: 1232 }] },
            { episode: "73-qism", name: "", posts: [{ post_id: 1233 }] },
            { episode: "74-qism", name: "", posts: [{ post_id: 1234 }] },
            { episode: "75-qism", name: "", posts: [{ post_id: 1235 }] },
            { episode: "76-qism", name: "", posts: [{ post_id: 1236 }] },
            { episode: "77-qism", name: "", posts: [{ post_id: 1237 }] },
            { episode: "78-qism", name: "", posts: [{ post_id: 1238 }] },
            { episode: "79-qism", name: "", posts: [{ post_id: 1239 }] },
            { episode: "80-qism", name: "", posts: [{ post_id: 1240 }] },
            { episode: "81-qism", name: "", posts: [{ post_id: 1241 }] },
            { episode: "82-qism", name: "", posts: [{ post_id: 1242 }] },
            { episode: "83-qism", name: "", posts: [{ post_id: 1243 }] },
            { episode: "84-qism", name: "", posts: [{ post_id: 1244 }] },
            { episode: "85-qism", name: "", posts: [{ post_id: 1245 }] },
            { episode: "86-qism", name: "", posts: [{ post_id: 1246 }] },
            { episode: "87-qism", name: "", posts: [{ post_id: 1247 }] },
            { episode: "88-qism", name: "", posts: [{ post_id: 1248 }] },
            { episode: "89-qism", name: "", posts: [{ post_id: 1249 }] },
            { episode: "90-qism", name: "", posts: [{ post_id: 1250 }] },
            { episode: "91-qism", name: "", posts: [{ post_id: 1251 }] },
            { episode: "92-qism", name: "", posts: [{ post_id: 1252 }] },
            { episode: "93-qism", name: "", posts: [{ post_id: 1253 }] },
            { episode: "94-qism", name: "", posts: [{ post_id: 1254 }] },
            { episode: "95-qism", name: "", posts: [{ post_id: 1255 }] },
            { episode: "96-qism", name: "", posts: [{ post_id: 1256 }] },
            { episode: "97-qism", name: "", posts: [{ post_id: 1257 }] },
            { episode: "98-qism", name: "", posts: [{ post_id: 1258 }] },
            { episode: "99-qism", name: "", posts: [{ post_id: 1259 }] },
            { episode: "100-qism", name: "", posts: [{ post_id: 1260 }] },
            { episode: "101-qism", name: "", posts: [{ post_id: 1261 }] },
            { episode: "102-qism", name: "", posts: [{ post_id: 1262 }] },
            { episode: "103-qism", name: "", posts: [{ post_id: 1263 }] },
            { episode: "104-qism", name: "", posts: [{ post_id: 1264 }] },
            { episode: "105-qism", name: "", posts: [{ post_id: 1265 }] },
            { episode: "106-qism", name: "", posts: [{ post_id: 1266 }] },
            { episode: "107-qism", name: "", posts: [{ post_id: 1267 }] },
            { episode: "108-qism", name: "", posts: [{ post_id: 1268 }] },
            { episode: "109-qism", name: "", posts: [{ post_id: 1269 }] },
            { episode: "110-qism", name: "", posts: [{ post_id: 1270 }] },
            { episode: "111-qism", name: "", posts: [{ post_id: 1271 }] },
            { episode: "112-qism", name: "", posts: [{ post_id: 1272 }] },
            { episode: "113-qism", name: "", posts: [{ post_id: 1273 }] },
            { episode: "114-qism", name: "", posts: [{ post_id: 1274 }] },
            { episode: "115-qism", name: "", posts: [{ post_id: 1275 }] },
            { episode: "116-qism", name: "", posts: [{ post_id: 1276 }] },
            { episode: "117-qism", name: "", posts: [{ post_id: 1277 }] },
            { episode: "118-qism", name: "", posts: [{ post_id: 1278 }] },
            { episode: "119-qism", name: "", posts: [{ post_id: 1279 }] },
            { episode: "120-qism", name: "", posts: [{ post_id: 1280 }] },
            { episode: "121-qism", name: "", posts: [{ post_id: 1281 }] },
            { episode: "122-qism", name: "", posts: [{ post_id: 1282 }] },
            { episode: "123-qism", name: "", posts: [{ post_id: 1283 }] },
            { episode: "124-qism", name: "", posts: [{ post_id: 1284 }] },
            { episode: "125-qism", name: "", posts: [{ post_id: 1285 }] },
            { episode: "126-qism", name: "", posts: [{ post_id: 1286 }] },
            { episode: "127-qism", name: "", posts: [{ post_id: 1287 }] },
            { episode: "128-qism", name: "", posts: [{ post_id: 1288 }] },
            { episode: "129-qism", name: "", posts: [{ post_id: 1289 }] },
            { episode: "130-qism", name: "", posts: [{ post_id: 1290 }] },
            { episode: "131-qism", name: "", posts: [{ post_id: 1291 }] },
            { episode: "132-qism", name: "", posts: [{ post_id: 1292 }] },
            { episode: "133-qism", name: "", posts: [{ post_id: 1293 }] },
            { episode: "134-qism", name: "", posts: [{ post_id: 1294 }] },
            { episode: "135-qism", name: "", posts: [{ post_id: 1295 }] },
            { episode: "136-qism", name: "", posts: [{ post_id: 1296 }] },
            { episode: "137-qism", name: "", posts: [{ post_id: 1297 }] },
            { episode: "138-qism", name: "", posts: [{ post_id: 1298 }] },
            { episode: "139-qism", name: "", posts: [{ post_id: 1299 }] },
            { episode: "140-qism", name: "", posts: [{ post_id: 1300 }] },
            { episode: "141-qism", name: "", posts: [{ post_id: 1301 }] },
            { episode: "142-qism", name: "", posts: [{ post_id: 1302 }] },
            { episode: "143-qism", name: "", posts: [{ post_id: 1303 }] },
            { episode: "144-qism", name: "", posts: [{ post_id: 1304 }] },
            { episode: "145-qism", name: "", posts: [{ post_id: 1305 }] },
            { episode: "146-qism", name: "", posts: [{ post_id: 1306 }] },
            { episode: "147-qism", name: "", posts: [{ post_id: 1307 }] },
            { episode: "148-qism", name: "", posts: [{ post_id: 1308 }] },
            { episode: "149-qism", name: "", posts: [{ post_id: 1309 }] },
            { episode: "150-qism", name: "", posts: [{ post_id: 1310 }] },
            { episode: "151-qism", name: "", posts: [{ post_id: 1311 }] },
            { episode: "152-qism", name: "", posts: [{ post_id: 1312 }] },
            { episode: "153-qism", name: "", posts: [{ post_id: 1313 }] },
            { episode: "154-qism", name: "", posts: [{ post_id: 1314 }] },
            { episode: "155-qism", name: "", posts: [{ post_id: 1315 }] },
            { episode: "156-qism", name: "", posts: [{ post_id: 1316 }] },
            { episode: "157-qism", name: "", posts: [{ post_id: 1317 }] },
            { episode: "158-qism", name: "", posts: [{ post_id: 1318 }] },
            { episode: "159-qism", name: "", posts: [{ post_id: 1319 }] },
            { episode: "160-qism", name: "", posts: [{ post_id: 1320 }] },
            { episode: "161-qism", name: "", posts: [{ post_id: 1321 }] },
            { episode: "162-qism", name: "", posts: [{ post_id: 1322 }] },
            { episode: "163-qism", name: "", posts: [{ post_id: 1323 }] },
            { episode: "164-qism", name: "", posts: [{ post_id: 1324 }] },
            { episode: "165-qism", name: "", posts: [{ post_id: 1325 }] },
            { episode: "166-qism", name: "", posts: [{ post_id: 1326 }] },
            { episode: "167-qism", name: "", posts: [{ post_id: 1327 }] },
            { episode: "168-qism", name: "", posts: [{ post_id: 1328 }] },
            { episode: "169-qism", name: "", posts: [{ post_id: 1329 }] },
            { episode: "170-qism", name: "", posts: [{ post_id: 1330 }] },
            { episode: "171-qism", name: "", posts: [{ post_id: 1331 }] },
            { episode: "172-qism", name: "", posts: [{ post_id: 1332 }] },
            { episode: "173-qism", name: "", posts: [{ post_id: 1333 }] },
            { episode: "174-qism", name: "", posts: [{ post_id: 1334 }] },
            { episode: "175-qism", name: "", posts: [{ post_id: 1335 }] },
            { episode: "176-qism", name: "", posts: [{ post_id: 1336 }] },
            { episode: "177-qism", name: "", posts: [{ post_id: 1337 }] },
            { episode: "178-qism", name: "", posts: [{ post_id: 1338 }] },
            { episode: "179-qism", name: "", posts: [{ post_id: 1339 }] },
            { episode: "180-qism", name: "", posts: [{ post_id: 1340 }] },
            { episode: "181-qism", name: "", posts: [{ post_id: 1341 }] },
            { episode: "182-qism", name: "", posts: [{ post_id: 1342 }] },
            { episode: "183-qism", name: "", posts: [{ post_id: 1343 }] },
            { episode: "184-qism", name: "", posts: [{ post_id: 1344 }] },
            { episode: "185-qism", name: "", posts: [{ post_id: 1345 }] },
            { episode: "186-qism", name: "", posts: [{ post_id: 1346 }] },
            { episode: "187-qism", name: "", posts: [{ post_id: 1347 }] },
            { episode: "188-qism", name: "", posts: [{ post_id: 1348 }] },
            { episode: "189-qism", name: "", posts: [{ post_id: 1349 }] },
            { episode: "190-qism", name: "", posts: [{ post_id: 1350 }] },
            { episode: "191-qism", name: "", posts: [{ post_id: 1351 }] },
            { episode: "192-qism", name: "", posts: [{ post_id: 1352 }] },
            { episode: "193-qism", name: "", posts: [{ post_id: 1353 }] },
            { episode: "194-qism", name: "", posts: [{ post_id: 1354 }] },
            { episode: "195-qism", name: "", posts: [{ post_id: 1355 }] },
            { episode: "196-qism", name: "", posts: [{ post_id: 1356 }] },
            { episode: "197-qism", name: "", posts: [{ post_id: 1357 }] },
            { episode: "198-qism", name: "", posts: [{ post_id: 1358 }] },
            { episode: "199-qism", name: "", posts: [{ post_id: 1359 }] },
            { episode: "200-qism", name: "", posts: [{ post_id: 1360 }] },
            { episode: "201-qism", name: "", posts: [{ post_id: 1361 }] },
            { episode: "202-qism", name: "", posts: [{ post_id: 1362 }] },
        ];

        const anibla = await knex("dub").where("name", "Anibla").first();
        data.forEach((e) => (e.dub = anibla.id));
        const anime = await knex("anime").insert({ name: "One piece", number_of_episode: 0, status: "ongoing" }).returning("*");

        for (const item of data) {
            item.anime_id = anime[0].id;
            const post = item.posts;
            delete item.posts;
            const episode = await knex("episode").insert(item).returning("*");

            post.forEach((e) => (e.episode_id = episode[0].id));
            await knex("channel_post").insert(post);
        }
    } catch (error) {
        console.error(error);
    }
}

insert().then(() => console.log("Data inserted successfully!"));
